from dataclasses import dataclass

from src.domain.enums import AssessmentVerdict, ReviewStatus
from src.standards.evidence_ontology import EvidenceKind, RequirementFacet, SemanticGroup


@dataclass(frozen=True)
class RequirementEvidenceContract:
    requirement_id: str
    allowed_pages: tuple[int, ...] = ()
    forbidden_pages: tuple[int, ...] = ()
    candidate_pages: tuple[int, ...] | None = None
    kpi_table_pages: tuple[int, ...] = ()
    verdict: AssessmentVerdict | None = None
    review_status: ReviewStatus | None = None
    rationale: str | None = None
    missing_items: tuple[str, ...] = ()
    facets: tuple[RequirementFacet, ...] = ()
    evidence_kinds: tuple[EvidenceKind, ...] = ()
    semantic_group: SemanticGroup | None = None


_CONTRACTS: dict[str, RequirementEvidenceContract] = {
    "GRI 205-1-a": RequirementEvidenceContract(
        requirement_id="GRI 205-1-a",
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_PERCENTAGE),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.ANTI_CORRUPTION_RISK,
        missing_items=("接受腐败风险评估的运营点总数", "接受腐败风险评估的运营点百分比"),
    ),
    "GRI 205-1-b": RequirementEvidenceContract(
        requirement_id="GRI 205-1-b",
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.ANTI_CORRUPTION_RISK,
        missing_items=("重大腐败风险类型", "风险涉及的业务环节或地点"),
    ),
    "GRI 302-1-a": RequirementEvidenceContract(
        requirement_id="GRI 302-1-a",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.ENERGY_KPI,
        missing_items=("完整能源类型和单位口径", "热力、制冷、蒸汽要素", "编制方法人工复核"),
    ),
    "GRI 302-1-c": RequirementEvidenceContract(
        requirement_id="GRI 302-1-c",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.ENERGY_KPI,
        missing_items=("完整能源类型和单位口径", "热力、制冷、蒸汽要素", "编制方法人工复核"),
    ),
    "GRI 302-1-e": RequirementEvidenceContract(
        requirement_id="GRI 302-1-e",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.ENERGY_KPI,
    ),
    "GRI 302-4-a": RequirementEvidenceContract(
        requirement_id="GRI 302-4-a",
        allowed_pages=(23, 63),
        candidate_pages=(23, 63),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.ENERGY_KPI,
        missing_items=("完整能源类型", "节能量计算基准", "计算方法、假设或工具"),
    ),
    "GRI 302-4-b": RequirementEvidenceContract(
        requirement_id="GRI 302-4-b",
        allowed_pages=(23, 63),
        candidate_pages=(23, 63),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.ENERGY_KPI,
        missing_items=("完整能源类型", "节能量计算基准", "计算方法、假设或工具"),
    ),
    "GRI 303-1-a": RequirementEvidenceContract(
        requirement_id="GRI 303-1-a",
        allowed_pages=(25, 63),
        candidate_pages=(25, 63),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-1-b": RequirementEvidenceContract(
        requirement_id="GRI 303-1-b",
        allowed_pages=(25,),
        candidate_pages=(25,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-1-c": RequirementEvidenceContract(
        requirement_id="GRI 303-1-c",
        allowed_pages=(22, 25),
        candidate_pages=(22, 25),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-1-d": RequirementEvidenceContract(
        requirement_id="GRI 303-1-d",
        allowed_pages=(16, 25),
        candidate_pages=(16, 25),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-2-a": RequirementEvidenceContract(
        requirement_id="GRI 303-2-a",
        allowed_pages=(22,),
        candidate_pages=(22,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-2-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 303-2-a-ii",
        allowed_pages=(22, 25),
        candidate_pages=(22, 25),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-3-a": RequirementEvidenceContract(
        requirement_id="GRI 303-3-a",
        allowed_pages=(25, 63),
        candidate_pages=(25, 63),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-3-a-i": RequirementEvidenceContract(
        requirement_id="GRI 303-3-a-i",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-3-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 303-3-a-ii",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-3-a-v": RequirementEvidenceContract(
        requirement_id="GRI 303-3-a-v",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-3-b": RequirementEvidenceContract(
        requirement_id="GRI 303-3-b",
        allowed_pages=(25, 63),
        candidate_pages=(25, 63),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-3-c": RequirementEvidenceContract(
        requirement_id="GRI 303-3-c",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-3-c-i": RequirementEvidenceContract(
        requirement_id="GRI 303-3-c-i",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-3-c-ii": RequirementEvidenceContract(
        requirement_id="GRI 303-3-c-ii",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-4-a": RequirementEvidenceContract(
        requirement_id="GRI 303-4-a",
        allowed_pages=(22, 63),
        candidate_pages=(22, 63),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-4-b": RequirementEvidenceContract(
        requirement_id="GRI 303-4-b",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-4-b-i": RequirementEvidenceContract(
        requirement_id="GRI 303-4-b-i",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 303-4-b-ii": RequirementEvidenceContract(
        requirement_id="GRI 303-4-b-ii",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WATER_KPI,
        missing_items=("完整水源或排放目的地拆分", "高水风险区域拆分", "内部标准或方法说明", "数据编制方法"),
    ),
    "GRI 305-1-a": RequirementEvidenceContract(
        requirement_id="GRI 305-1-a",
        allowed_pages=(20, 63),
        forbidden_pages=(3,),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
    ),
    "GRI 305-1-e": RequirementEvidenceContract(
        requirement_id="GRI 305-1-e",
        allowed_pages=(64,),
        candidate_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.METHODOLOGY,),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
        missing_items=("温室气体种类", "完整排放因子来源", "完整 GWP 来源"),
    ),
    "GRI 305-1-g": RequirementEvidenceContract(
        requirement_id="GRI 305-1-g",
        allowed_pages=(64,),
        candidate_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.METHODOLOGY,),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
        missing_items=("完整核算标准", "完整方法说明"),
    ),
    "GRI 305-2-a": RequirementEvidenceContract(
        requirement_id="GRI 305-2-a",
        allowed_pages=(20, 63),
        forbidden_pages=(3,),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
    ),
    "GRI 305-2-b": RequirementEvidenceContract(
        requirement_id="GRI 305-2-b",
        allowed_pages=(20, 63),
        forbidden_pages=(3,),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
    ),
    "GRI 305-2-c": RequirementEvidenceContract(
        requirement_id="GRI 305-2-c",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE, EvidenceKind.METHODOLOGY),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
    ),
    "GRI 305-2-d": RequirementEvidenceContract(
        requirement_id="GRI 305-2-d",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE, EvidenceKind.METHODOLOGY),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
    ),
    "GRI 305-2-d-i": RequirementEvidenceContract(
        requirement_id="GRI 305-2-d-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE, EvidenceKind.METHODOLOGY),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
    ),
    "GRI 305-2-e": RequirementEvidenceContract(
        requirement_id="GRI 305-2-e",
        allowed_pages=(64,),
        candidate_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.METHODOLOGY,),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
        missing_items=("GWP rates", "完整排放因子适用口径"),
    ),
    "GRI 305-2-g": RequirementEvidenceContract(
        requirement_id="GRI 305-2-g",
        allowed_pages=(64,),
        forbidden_pages=(3,),
        candidate_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.METHODOLOGY,),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
        missing_items=("完整核算标准", "完整方法、假设和计算工具"),
    ),
    "GRI 305-3-a": RequirementEvidenceContract(
        requirement_id="GRI 305-3-a",
        allowed_pages=(20, 63),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
    ),
    "GRI 305-3-f": RequirementEvidenceContract(
        requirement_id="GRI 305-3-f",
        allowed_pages=(64,),
        candidate_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.METHODOLOGY,),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
        missing_items=("GWP rates", "完整范围三排放因子口径"),
    ),
    "GRI 305-5-a": RequirementEvidenceContract(
        requirement_id="GRI 305-5-a",
        allowed_pages=(63,),
        kpi_table_pages=(63,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
    ),
    "GRI 305-7-a": RequirementEvidenceContract(
        requirement_id="GRI 305-7-a",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE, EvidenceKind.METHODOLOGY),
        semantic_group=SemanticGroup.GHG_EMISSIONS_KPI,
    ),
    "GRI 306-1-a": RequirementEvidenceContract(
        requirement_id="GRI 306-1-a",
        allowed_pages=(21, 22),
        candidate_pages=(21, 22),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("完整重大影响识别", "上下游边界说明"),
    ),
    "GRI 306-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 306-1-a-i",
        allowed_pages=(21,),
        candidate_pages=(21,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("完整 input/activity/output 映射",),
    ),
    "GRI 306-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 306-1-a-ii",
        allowed_pages=(21,),
        candidate_pages=(21,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("完整价值链废弃物影响边界",),
    ),
    "GRI 306-2-a": RequirementEvidenceContract(
        requirement_id="GRI 306-2-a",
        allowed_pages=(21,),
        candidate_pages=(21,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("完整行动清单", "覆盖范围和效果"),
    ),
    "GRI 306-2-b": RequirementEvidenceContract(
        requirement_id="GRI 306-2-b",
        allowed_pages=(21,),
        candidate_pages=(21,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("第三方处置过程完整说明", "覆盖范围和审查标准"),
    ),
    "GRI 306-3-a": RequirementEvidenceContract(
        requirement_id="GRI 306-3-a",
        allowed_pages=(64,),
        kpi_table_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("废弃物组成", "数据编制上下文"),
    ),
    "GRI 306-4-a": RequirementEvidenceContract(
        requirement_id="GRI 306-4-a",
        allowed_pages=(64,),
        kpi_table_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("recovery operation 拆分", "处置去向拆分"),
    ),
    "GRI 306-4-b": RequirementEvidenceContract(
        requirement_id="GRI 306-4-b",
        allowed_pages=(64,),
        kpi_table_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("危险废弃物 recovery operation 拆分",),
    ),
    "GRI 306-4-c": RequirementEvidenceContract(
        requirement_id="GRI 306-4-c",
        allowed_pages=(64,),
        kpi_table_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("非危险废弃物 recovery operation 拆分",),
    ),
    "GRI 306-4-b-i": RequirementEvidenceContract(
        requirement_id="GRI 306-4-b-i",
        allowed_pages=(21, 64),
        candidate_pages=(21, 64),
        kpi_table_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("回用废弃物总重量", "处置去向或场内外拆分"),
    ),
    "GRI 306-4-c-i": RequirementEvidenceContract(
        requirement_id="GRI 306-4-c-i",
        allowed_pages=(21, 64),
        candidate_pages=(21, 64),
        kpi_table_pages=(64,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.WASTE_KPI,
        missing_items=("回用废弃物总重量", "处置去向或场内外拆分"),
    ),
    "GRI 308-1-a": RequirementEvidenceContract(
        requirement_id="GRI 308-1-a",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_NEW_SUPPLIER_SCOPE),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
    ),
    "GRI 308-2-a": RequirementEvidenceContract(
        requirement_id="GRI 308-2-a",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
    ),
    "GRI 308-2-b": RequirementEvidenceContract(
        requirement_id="GRI 308-2-b",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
    ),
    "GRI 308-2-c": RequirementEvidenceContract(
        requirement_id="GRI 308-2-c",
        allowed_pages=(52, 67),
        candidate_pages=(52, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
        missing_items=("供应链重大环境影响类型",),
    ),
    "GRI 308-2-d": RequirementEvidenceContract(
        requirement_id="GRI 308-2-d",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
    ),
    "GRI 308-2-e": RequirementEvidenceContract(
        requirement_id="GRI 308-2-e",
        allowed_pages=(54, 67),
        candidate_pages=(54, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_REASON_WHY),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
        missing_items=("终止关系原因说明",),
    ),
    "GRI 401-1-a": RequirementEvidenceContract(
        requirement_id="GRI 401-1-a",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_REGION_BREAKDOWN),
        evidence_kinds=(EvidenceKind.KPI_BREAKDOWN,),
        semantic_group=SemanticGroup.EMPLOYEE_KPI,
        missing_items=("地区拆分",),
    ),
    "GRI 401-1-b": RequirementEvidenceContract(
        requirement_id="GRI 401-1-b",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_REGION_BREAKDOWN),
        evidence_kinds=(EvidenceKind.KPI_BREAKDOWN,),
        semantic_group=SemanticGroup.EMPLOYEE_KPI,
        missing_items=("地区拆分",),
    ),
    "GRI 401-2-a": RequirementEvidenceContract(
        requirement_id="GRI 401-2-a",
        allowed_pages=(34,),
        candidate_pages=(34,),
        facets=(RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN, RequirementFacet.REQUIRES_REGION_BREAKDOWN),
        evidence_kinds=(EvidenceKind.POLICY,),
        semantic_group=SemanticGroup.BENEFITS_POLICY,
        missing_items=("全职与临时/兼职员工福利差异", "significant locations of operation"),
    ),
    "GRI 401-2-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 401-2-a-ii",
        allowed_pages=(34,),
        candidate_pages=(34,),
        facets=(RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN, RequirementFacet.REQUIRES_REGION_BREAKDOWN),
        evidence_kinds=(EvidenceKind.POLICY,),
        semantic_group=SemanticGroup.BENEFITS_POLICY,
        missing_items=("员工类别福利差异", "significant locations of operation"),
    ),
    "GRI 401-2-a-iv": RequirementEvidenceContract(
        requirement_id="GRI 401-2-a-iv",
        allowed_pages=(34,),
        candidate_pages=(34,),
        facets=(RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN, RequirementFacet.REQUIRES_REGION_BREAKDOWN),
        evidence_kinds=(EvidenceKind.POLICY,),
        semantic_group=SemanticGroup.BENEFITS_POLICY,
        missing_items=("员工类别福利差异", "significant locations of operation"),
    ),
    "GRI 401-2-a-vii": RequirementEvidenceContract(
        requirement_id="GRI 401-2-a-vii",
        allowed_pages=(34,),
        candidate_pages=(34,),
        facets=(RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN, RequirementFacet.REQUIRES_REGION_BREAKDOWN),
        evidence_kinds=(EvidenceKind.POLICY,),
        semantic_group=SemanticGroup.BENEFITS_POLICY,
        missing_items=("员工类别福利差异", "significant locations of operation"),
    ),
    "GRI 401-3-c": RequirementEvidenceContract(
        requirement_id="GRI 401-3-c",
        allowed_pages=(66,),
        forbidden_pages=(32,),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_GENDER_BREAKDOWN),
        evidence_kinds=(EvidenceKind.KPI_BREAKDOWN,),
        semantic_group=SemanticGroup.EMPLOYEE_KPI,
    ),
    "GRI 401-3-d": RequirementEvidenceContract(
        requirement_id="GRI 401-3-d",
        allowed_pages=(66,),
        forbidden_pages=(32,),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_GENDER_BREAKDOWN),
        evidence_kinds=(EvidenceKind.KPI_BREAKDOWN,),
        semantic_group=SemanticGroup.EMPLOYEE_KPI,
    ),
    "GRI 401-3-e": RequirementEvidenceContract(
        requirement_id="GRI 401-3-e",
        allowed_pages=(66,),
        forbidden_pages=(32,),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_GENDER_BREAKDOWN),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.EMPLOYEE_KPI,
        missing_items=("按性别披露的返岗率和留任率",),
    ),
    "GRI 402-1-a": RequirementEvidenceContract(
        requirement_id="GRI 402-1-a",
        allowed_pages=(33, 66),
        candidate_pages=(33, 66),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.NOTICE_PERIOD,
    ),
    "GRI 402-1-b": RequirementEvidenceContract(
        requirement_id="GRI 402-1-b",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.NOTICE_PERIOD,
    ),
    "GRI 403-1-a": RequirementEvidenceContract(
        requirement_id="GRI 403-1-a",
        allowed_pages=(38, 39, 66),
        candidate_pages=(38, 39, 66),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("覆盖范围", "排除说明"),
    ),
    "GRI 403-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 403-1-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
    ),
    "GRI 403-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-1-a-ii",
        allowed_pages=(38, 39, 66),
        candidate_pages=(38, 39, 66),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("完整标准/指南", "覆盖范围"),
    ),
    "GRI 403-1-b": RequirementEvidenceContract(
        requirement_id="GRI 403-1-b",
        allowed_pages=(38, 39, 66),
        candidate_pages=(38, 39, 66),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_WORKER_BOUNDARY, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("人员、活动和工作场所覆盖范围", "排除说明"),
    ),
    "GRI 403-2-a": RequirementEvidenceContract(
        requirement_id="GRI 403-2-a",
        allowed_pages=(39, 41),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("完整流程和覆盖范围",),
    ),
    "GRI 403-2-a-i": RequirementEvidenceContract(
        requirement_id="GRI 403-2-a-i",
        allowed_pages=(39, 41),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("常规/非常规危害识别流程",),
    ),
    "GRI 403-2-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-2-a-ii",
        allowed_pages=(39, 41),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("完整上报渠道", "保护机制"),
    ),
    "GRI 403-2-b": RequirementEvidenceContract(
        requirement_id="GRI 403-2-b",
        allowed_pages=(39, 41),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("事故调查流程细节",),
    ),
    "GRI 403-2-c": RequirementEvidenceContract(
        requirement_id="GRI 403-2-c",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
    ),
    "GRI 403-2-d": RequirementEvidenceContract(
        requirement_id="GRI 403-2-d",
        allowed_pages=(39, 41),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("调查结果纳入体系改进的完整机制",),
    ),
    "GRI 403-3-a": RequirementEvidenceContract(
        requirement_id="GRI 403-3-a",
        allowed_pages=(38, 66, 67),
        candidate_pages=(38, 66, 67),
        kpi_table_pages=(66, 67),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("职业健康服务职能", "质量保证", "员工获取方式"),
    ),
    "GRI 403-4-a": RequirementEvidenceContract(
        requirement_id="GRI 403-4-a",
        allowed_pages=(38, 39, 41, 66),
        candidate_pages=(38, 39, 41, 66),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("委员会职责", "会议频率", "决策权限"),
    ),
    "GRI 403-4-b": RequirementEvidenceContract(
        requirement_id="GRI 403-4-b",
        allowed_pages=(38, 39, 41, 66),
        candidate_pages=(38, 39, 41, 66),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("委员会职责", "未代表员工原因"),
    ),
    "GRI 403-5-a": RequirementEvidenceContract(
        requirement_id="GRI 403-5-a",
        allowed_pages=(41, 66),
        candidate_pages=(41, 66),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("hazard-specific training 细节",),
    ),
    "GRI 403-6-a": RequirementEvidenceContract(
        requirement_id="GRI 403-6-a",
        allowed_pages=(34, 66, 67),
        candidate_pages=(34, 66, 67),
        kpi_table_pages=(66, 67),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("获取方式", "服务范围"),
    ),
    "GRI 403-6-b": RequirementEvidenceContract(
        requirement_id="GRI 403-6-b",
        allowed_pages=(34, 67),
        candidate_pages=(34, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("重大非工作相关健康风险", "健康促进项目", "获取方式"),
    ),
    "GRI 403-7-a": RequirementEvidenceContract(
        requirement_id="GRI 403-7-a",
        allowed_pages=(38, 39, 41, 52, 53, 54),
        candidate_pages=(38, 39, 41, 52, 53, 54),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION, RequirementFacet.REQUIRES_WORKER_BOUNDARY),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("业务关系相关 OHS 影响预防和缓解全过程",),
    ),
    "GRI 403-8-a": RequirementEvidenceContract(
        requirement_id="GRI 403-8-a",
        allowed_pages=(38, 39, 66),
        candidate_pages=(38, 39, 66),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_WORKER_BOUNDARY),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("员工和非雇员工作者覆盖人数及比例",),
    ),
    "GRI 403-8-a-i": RequirementEvidenceContract(
        requirement_id="GRI 403-8-a-i",
        allowed_pages=(66,),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_WORKER_BOUNDARY),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("员工覆盖人数及比例",),
    ),
    "GRI 403-8-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-8-a-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_WORKER_BOUNDARY, RequirementFacet.REQUIRES_PERCENTAGE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
    ),
    "GRI 403-8-a-iii": RequirementEvidenceContract(
        requirement_id="GRI 403-8-a-iii",
        allowed_pages=(66,),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("内部审核或认证覆盖人数及比例",),
    ),
    "GRI 403-8-b": RequirementEvidenceContract(
        requirement_id="GRI 403-8-b",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_WORKER_BOUNDARY,),
        evidence_kinds=(EvidenceKind.KPI_VALUE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
    ),
    "GRI 403-8-c": RequirementEvidenceContract(
        requirement_id="GRI 403-8-c",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
    ),
    "GRI 403-9-a": RequirementEvidenceContract(
        requirement_id="GRI 403-9-a",
        allowed_pages=(40, 67),
        candidate_pages=(40, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("高后果工伤拆分", "完整方法说明"),
    ),
    "GRI 403-9-a-i": RequirementEvidenceContract(
        requirement_id="GRI 403-9-a-i",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("死亡率",),
    ),
    "GRI 403-9-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-9-a-ii",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_IMPACT_TYPE),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("高后果工伤数量和率",),
    ),
    "GRI 403-9-a-iii": RequirementEvidenceContract(
        requirement_id="GRI 403-9-a-iii",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-9-a-iv": RequirementEvidenceContract(
        requirement_id="GRI 403-9-a-iv",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-9-a-v": RequirementEvidenceContract(
        requirement_id="GRI 403-9-a-v",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-9-b": RequirementEvidenceContract(
        requirement_id="GRI 403-9-b",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_WORKER_BOUNDARY),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("受组织控制的非雇员工作者口径",),
    ),
    "GRI 403-9-b-i": RequirementEvidenceContract(
        requirement_id="GRI 403-9-b-i",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_WORKER_BOUNDARY),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("受组织控制的非雇员工作者口径",),
    ),
    "GRI 403-9-b-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-9-b-ii",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(
            RequirementFacet.REQUIRES_COUNT,
            RequirementFacet.REQUIRES_WORKER_BOUNDARY,
            RequirementFacet.REQUIRES_IMPACT_TYPE,
        ),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("高后果工伤数量和率", "受组织控制的非雇员工作者口径"),
    ),
    "GRI 403-9-b-iii": RequirementEvidenceContract(
        requirement_id="GRI 403-9-b-iii",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_WORKER_BOUNDARY),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("受组织控制的非雇员工作者口径",),
    ),
    "GRI 403-9-b-iv": RequirementEvidenceContract(
        requirement_id="GRI 403-9-b-iv",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE, RequirementFacet.REQUIRES_WORKER_BOUNDARY,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-9-b-v": RequirementEvidenceContract(
        requirement_id="GRI 403-9-b-v",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_WORKER_BOUNDARY),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("受组织控制的非雇员工作者口径",),
    ),
    "GRI 403-9-c": RequirementEvidenceContract(
        requirement_id="GRI 403-9-c",
        allowed_pages=(40, 67),
        candidate_pages=(40, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("完整高后果工伤危害清单",),
    ),
    "GRI 403-9-c-i": RequirementEvidenceContract(
        requirement_id="GRI 403-9-c-i",
        allowed_pages=(40,),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("高后果工伤危害清单",),
    ),
    "GRI 403-9-c-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-9-c-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-9-c-iii": RequirementEvidenceContract(
        requirement_id="GRI 403-9-c-iii",
        allowed_pages=(40,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("完整行动及效果说明",),
    ),
    "GRI 403-9-d": RequirementEvidenceContract(
        requirement_id="GRI 403-9-d",
        allowed_pages=(40, 67),
        candidate_pages=(40, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("完整控制层级行动说明",),
    ),
    "GRI 403-9-e": RequirementEvidenceContract(
        requirement_id="GRI 403-9-e",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.METHODOLOGY,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-9-f": RequirementEvidenceContract(
        requirement_id="GRI 403-9-f",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-9-g": RequirementEvidenceContract(
        requirement_id="GRI 403-9-g",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-10-a": RequirementEvidenceContract(
        requirement_id="GRI 403-10-a",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("完整 work-related ill health 口径",),
    ),
    "GRI 403-10-a-i": RequirementEvidenceContract(
        requirement_id="GRI 403-10-a-i",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-10-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-10-a-ii",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("完整可记录工作相关健康问题口径",),
    ),
    "GRI 403-10-a-iii": RequirementEvidenceContract(
        requirement_id="GRI 403-10-a-iii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-10-b": RequirementEvidenceContract(
        requirement_id="GRI 403-10-b",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(
            RequirementFacet.REQUIRES_COUNT,
            RequirementFacet.REQUIRES_WORKER_BOUNDARY,
            RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,
        ),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("受组织控制的非雇员工作者口径", "完整 work-related ill health 口径"),
    ),
    "GRI 403-10-b-i": RequirementEvidenceContract(
        requirement_id="GRI 403-10-b-i",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_WORKER_BOUNDARY),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("受组织控制的非雇员工作者口径",),
    ),
    "GRI 403-10-b-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-10-b-ii",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(
            RequirementFacet.REQUIRES_COUNT,
            RequirementFacet.REQUIRES_WORKER_BOUNDARY,
            RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,
        ),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("受组织控制的非雇员工作者口径", "完整可记录工作相关健康问题口径"),
    ),
    "GRI 403-10-b-iii": RequirementEvidenceContract(
        requirement_id="GRI 403-10-b-iii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE, RequirementFacet.REQUIRES_WORKER_BOUNDARY,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-10-c": RequirementEvidenceContract(
        requirement_id="GRI 403-10-c",
        allowed_pages=(38, 67),
        candidate_pages=(38, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("完整工作相关健康问题危害清单",),
    ),
    "GRI 403-10-c-i": RequirementEvidenceContract(
        requirement_id="GRI 403-10-c-i",
        allowed_pages=(38, 67),
        candidate_pages=(38, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
        missing_items=("主要工作相关健康问题危害清单",),
    ),
    "GRI 403-10-c-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-10-c-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-10-c-iii": RequirementEvidenceContract(
        requirement_id="GRI 403-10-c-iii",
        allowed_pages=(38,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.OHS_MANAGEMENT,
        missing_items=("完整行动及效果说明",),
    ),
    "GRI 403-10-d": RequirementEvidenceContract(
        requirement_id="GRI 403-10-d",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 403-10-e": RequirementEvidenceContract(
        requirement_id="GRI 403-10-e",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.OHS_KPI,
    ),
    "GRI 404-1-a": RequirementEvidenceContract(
        requirement_id="GRI 404-1-a",
        allowed_pages=(35, 66),
        candidate_pages=(35, 66),
        kpi_table_pages=(66,),
        facets=(
            RequirementFacet.REQUIRES_GENDER_BREAKDOWN,
            RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN,
        ),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("按性别拆分", "按员工类别拆分"),
    ),
    "GRI 404-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 404-1-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_GENDER_BREAKDOWN,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
    ),
    "GRI 404-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 404-1-a-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
    ),
    "GRI 404-2-a": RequirementEvidenceContract(
        requirement_id="GRI 404-2-a",
        allowed_pages=(35, 36, 41),
        candidate_pages=(35, 36, 41),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.TRAINING_PROGRAM,
        missing_items=("完整技能提升项目说明",),
    ),
    "GRI 404-2-b": RequirementEvidenceContract(
        requirement_id="GRI 404-2-b",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.TRAINING_PROGRAM,
    ),
    "GRI 404-3-a": RequirementEvidenceContract(
        requirement_id="GRI 404-3-a",
        allowed_pages=(35, 66),
        candidate_pages=(35, 66),
        kpi_table_pages=(66,),
        facets=(
            RequirementFacet.REQUIRES_GENDER_BREAKDOWN,
            RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN,
        ),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("按性别拆分", "按员工类别拆分"),
    ),
    "GRI 405-1-a": RequirementEvidenceContract(
        requirement_id="GRI 405-1-a",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        facets=(RequirementFacet.REQUIRES_GOVERNANCE_BODY,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("治理机构完整组成", "治理机构口径确认"),
    ),
    "GRI 405-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 405-1-a-i",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        facets=(RequirementFacet.REQUIRES_GOVERNANCE_BODY, RequirementFacet.REQUIRES_GENDER_BREAKDOWN),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("治理机构多元化拆分", "治理机构口径确认"),
    ),
    "GRI 405-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 405-1-a-ii",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        facets=(RequirementFacet.REQUIRES_GOVERNANCE_BODY, RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("治理机构年龄组拆分", "治理机构口径确认"),
    ),
    "GRI 405-1-a-iii": RequirementEvidenceContract(
        requirement_id="GRI 405-1-a-iii",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        facets=(RequirementFacet.REQUIRES_GOVERNANCE_BODY, RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("治理机构其他多元化指标", "治理机构口径确认"),
    ),
    "GRI 405-1-b": RequirementEvidenceContract(
        requirement_id="GRI 405-1-b",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        facets=(
            RequirementFacet.REQUIRES_GENDER_BREAKDOWN,
            RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN,
        ),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("按员工类别交叉拆分",),
    ),
    "GRI 405-1-b-i": RequirementEvidenceContract(
        requirement_id="GRI 405-1-b-i",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        facets=(
            RequirementFacet.REQUIRES_GENDER_BREAKDOWN,
            RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN,
        ),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("按员工类别拆分的性别结构",),
    ),
    "GRI 405-1-b-ii": RequirementEvidenceContract(
        requirement_id="GRI 405-1-b-ii",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        facets=(RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("按员工类别拆分的年龄结构",),
    ),
    "GRI 405-1-b-iii": RequirementEvidenceContract(
        requirement_id="GRI 405-1-b-iii",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        facets=(RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("按员工类别拆分的其他多元化指标",),
    ),
    "GRI 405-2-a": RequirementEvidenceContract(
        requirement_id="GRI 405-2-a",
        allowed_pages=(33, 65, 66),
        candidate_pages=(33, 65, 66),
        kpi_table_pages=(65, 66),
        facets=(RequirementFacet.REQUIRES_EMPLOYEE_CATEGORY_BREAKDOWN, RequirementFacet.REQUIRES_REGION_BREAKDOWN),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
        missing_items=("按员工类别拆分", "重要运营地拆分"),
    ),
    "GRI 405-2-b": RequirementEvidenceContract(
        requirement_id="GRI 405-2-b",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_REGION_BREAKDOWN,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.BREAKDOWN_DIMENSION,
    ),
    "GRI 406-1-a": RequirementEvidenceContract(
        requirement_id="GRI 406-1-a",
        allowed_pages=(32,),
        candidate_pages=(32,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 406-1-b": RequirementEvidenceContract(
        requirement_id="GRI 406-1-b",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 406-1-b-i": RequirementEvidenceContract(
        requirement_id="GRI 406-1-b-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 406-1-b-ii": RequirementEvidenceContract(
        requirement_id="GRI 406-1-b-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 406-1-b-iii": RequirementEvidenceContract(
        requirement_id="GRI 406-1-b-iii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 406-1-b-iv": RequirementEvidenceContract(
        requirement_id="GRI 406-1-b-iv",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 407-1-a": RequirementEvidenceContract(
        requirement_id="GRI 407-1-a",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
    ),
    "GRI 407-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 407-1-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
    ),
    "GRI 407-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 407-1-a-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
    ),
    "GRI 407-1-b": RequirementEvidenceContract(
        requirement_id="GRI 407-1-b",
        allowed_pages=(33, 66),
        candidate_pages=(33, 66),
        kpi_table_pages=(66,),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
        missing_items=("风险运营点或供应商类别",),
    ),
    "GRI 408-1-a": RequirementEvidenceContract(
        requirement_id="GRI 408-1-a",
        allowed_pages=(32, 52, 53),
        candidate_pages=(32, 52, 53),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
        missing_items=("具体高风险运营点或供应商",),
    ),
    "GRI 408-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 408-1-a-i",
        allowed_pages=(32, 52),
        candidate_pages=(32, 52),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY,),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
        missing_items=("运营点童工风险识别结果",),
    ),
    "GRI 408-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 408-1-a-ii",
        allowed_pages=(32, 52, 53),
        candidate_pages=(32, 52, 53),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
        missing_items=("高风险供应商类型或地区", "风险识别结果"),
    ),
    "GRI 408-1-b": RequirementEvidenceContract(
        requirement_id="GRI 408-1-b",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
    ),
    "GRI 408-1-b-i": RequirementEvidenceContract(
        requirement_id="GRI 408-1-b-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
    ),
    "GRI 408-1-b-ii": RequirementEvidenceContract(
        requirement_id="GRI 408-1-b-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
    ),
    "GRI 408-1-c": RequirementEvidenceContract(
        requirement_id="GRI 408-1-c",
        allowed_pages=(32, 52, 53),
        candidate_pages=(32, 52, 53),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
        missing_items=("针对高风险运营点或供应商的措施",),
    ),
    "GRI 409-1-a": RequirementEvidenceContract(
        requirement_id="GRI 409-1-a",
        allowed_pages=(32, 52, 53),
        candidate_pages=(32, 52, 53),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
        missing_items=("高风险运营点或供应商识别结果",),
    ),
    "GRI 409-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 409-1-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
    ),
    "GRI 409-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 409-1-a-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
    ),
    "GRI 409-1-b": RequirementEvidenceContract(
        requirement_id="GRI 409-1-b",
        allowed_pages=(32, 52, 53),
        candidate_pages=(32, 52, 53),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.POLICY, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_POLICY,
        missing_items=("针对高风险运营点或供应商的措施",),
    ),
    "GRI 410-1-a": RequirementEvidenceContract(
        requirement_id="GRI 410-1-a",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_SECURITY_PERSONNEL, RequirementFacet.REQUIRES_PERCENTAGE,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM, EvidenceKind.POLICY,),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_TRAINING,
    ),
    "GRI 410-1-b": RequirementEvidenceContract(
        requirement_id="GRI 410-1-b",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_SECURITY_PERSONNEL,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM, EvidenceKind.POLICY,),
        semantic_group=SemanticGroup.HUMAN_RIGHTS_TRAINING,
    ),
    "GRI 413-1-a": RequirementEvidenceContract(
        requirement_id="GRI 413-1-a",
        allowed_pages=(14, 42, 43, 44),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_IMPACT_TYPE),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
        missing_items=("运营点比例", "社会影响评估覆盖"),
    ),
    "GRI 413-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 413-1-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE,),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
    ),
    "GRI 413-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 413-1-a-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE,),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
    ),
    "GRI 413-1-a-iii": RequirementEvidenceContract(
        requirement_id="GRI 413-1-a-iii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
    ),
    "GRI 413-1-a-iv": RequirementEvidenceContract(
        requirement_id="GRI 413-1-a-iv",
        allowed_pages=(14, 42),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE,),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
        missing_items=("运营点覆盖比例",),
    ),
    "GRI 413-1-a-v": RequirementEvidenceContract(
        requirement_id="GRI 413-1-a-v",
        allowed_pages=(14, 42, 43, 44),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
        missing_items=("是否基于利益相关方映射", "是否针对当地社区", "运营点覆盖范围"),
    ),
    "GRI 413-1-a-vi": RequirementEvidenceContract(
        requirement_id="GRI 413-1-a-vi",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
    ),
    "GRI 413-1-a-vii": RequirementEvidenceContract(
        requirement_id="GRI 413-1-a-vii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
    ),
    "GRI 413-1-a-viii": RequirementEvidenceContract(
        requirement_id="GRI 413-1-a-viii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
    ),
    "GRI 413-2-a": RequirementEvidenceContract(
        requirement_id="GRI 413-2-a",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
    ),
    "GRI 413-2-a-i": RequirementEvidenceContract(
        requirement_id="GRI 413-2-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
    ),
    "GRI 413-2-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 413-2-a-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_RISK_LOCATION,),
        evidence_kinds=(EvidenceKind.CASE, EvidenceKind.MANAGEMENT_MECHANISM),
        semantic_group=SemanticGroup.COMMUNITY_PROGRAM,
    ),
    "GRI 414-1-a": RequirementEvidenceContract(
        requirement_id="GRI 414-1-a",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_NEW_SUPPLIER_SCOPE),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
    ),
    "GRI 414-2-a": RequirementEvidenceContract(
        requirement_id="GRI 414-2-a",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
    ),
    "GRI 414-2-b": RequirementEvidenceContract(
        requirement_id="GRI 414-2-b",
        allowed_pages=(67,),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
    ),
    "GRI 414-2-c": RequirementEvidenceContract(
        requirement_id="GRI 414-2-c",
        allowed_pages=(52, 67),
        candidate_pages=(52, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_IMPACT_TYPE,),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
        missing_items=("供应链重大社会影响类型",),
    ),
    "GRI 414-2-d": RequirementEvidenceContract(
        requirement_id="GRI 414-2-d",
        allowed_pages=(54, 67),
        candidate_pages=(54, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
        missing_items=("与评估后改进行动相关的供应商比例",),
    ),
    "GRI 414-2-e": RequirementEvidenceContract(
        requirement_id="GRI 414-2-e",
        allowed_pages=(54, 67),
        candidate_pages=(54, 67),
        kpi_table_pages=(67,),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE, RequirementFacet.REQUIRES_REASON_WHY),
        evidence_kinds=(EvidenceKind.KPI_VALUE,),
        semantic_group=SemanticGroup.SUPPLIER_ASSESSMENT,
        missing_items=("终止关系百分比", "终止原因说明"),
    ),
    "GRI 416-2-a": RequirementEvidenceContract(
        requirement_id="GRI 416-2-a",
        allowed_pages=(46,),
        candidate_pages=(46,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
        missing_items=("法规不合规事件分类", "自愿准则不合规事件分类"),
    ),
    "GRI 416-2-a-i": RequirementEvidenceContract(
        requirement_id="GRI 416-2-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 416-2-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 416-2-a-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 416-2-a-iii": RequirementEvidenceContract(
        requirement_id="GRI 416-2-a-iii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 416-2-b": RequirementEvidenceContract(
        requirement_id="GRI 416-2-b",
        allowed_pages=(46,),
        candidate_pages=(46,),
        facets=(RequirementFacet.REQUIRES_COUNT, RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
        missing_items=("不合规事件口径",),
    ),
    "GRI 416-1-a": RequirementEvidenceContract(
        requirement_id="GRI 416-1-a",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.PRODUCT_INFORMATION,
    ),
    "GRI 417-1-a": RequirementEvidenceContract(
        requirement_id="GRI 417-1-a",
        allowed_pages=(46,),
        candidate_pages=(46,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.PRODUCT_INFORMATION,
        missing_items=("标签程序", "信息类型清单", "适用类别和覆盖比例"),
    ),
    "GRI 417-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 417-1-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.PRODUCT_INFORMATION,
    ),
    "GRI 417-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 417-1-a-ii",
        allowed_pages=(46,),
        candidate_pages=(46,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.PRODUCT_INFORMATION,
        missing_items=("信息类型清单", "适用类别和覆盖比例"),
    ),
    "GRI 417-1-a-iii": RequirementEvidenceContract(
        requirement_id="GRI 417-1-a-iii",
        allowed_pages=(46,),
        candidate_pages=(46,),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.PRODUCT_INFORMATION,
        missing_items=("标签程序", "覆盖比例"),
    ),
    "GRI 417-1-a-iv": RequirementEvidenceContract(
        requirement_id="GRI 417-1-a-iv",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.PRODUCT_INFORMATION,
    ),
    "GRI 417-1-a-v": RequirementEvidenceContract(
        requirement_id="GRI 417-1-a-v",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_METHOD_OR_ASSUMPTION,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.PRODUCT_INFORMATION,
    ),
    "GRI 417-1-b": RequirementEvidenceContract(
        requirement_id="GRI 417-1-b",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_PERCENTAGE,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM,),
        semantic_group=SemanticGroup.PRODUCT_INFORMATION,
    ),
    "GRI 417-2-a": RequirementEvidenceContract(
        requirement_id="GRI 417-2-a",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 417-2-a-i": RequirementEvidenceContract(
        requirement_id="GRI 417-2-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 417-2-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 417-2-a-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 417-2-a-iii": RequirementEvidenceContract(
        requirement_id="GRI 417-2-a-iii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 417-2-b": RequirementEvidenceContract(
        requirement_id="GRI 417-2-b",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 417-3-a": RequirementEvidenceContract(
        requirement_id="GRI 417-3-a",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 417-3-a-i": RequirementEvidenceContract(
        requirement_id="GRI 417-3-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 417-3-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 417-3-a-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 417-3-a-iii": RequirementEvidenceContract(
        requirement_id="GRI 417-3-a-iii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 417-3-b": RequirementEvidenceContract(
        requirement_id="GRI 417-3-b",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_INCIDENT_CLASSIFICATION,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 418-1-a": RequirementEvidenceContract(
        requirement_id="GRI 418-1-a",
        allowed_pages=(61,),
        candidate_pages=(61,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 418-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 418-1-a-i",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_COMPLAINT_SOURCE_BREAKDOWN,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 418-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 418-1-a-ii",
        candidate_pages=(),
        facets=(RequirementFacet.REQUIRES_COMPLAINT_SOURCE_BREAKDOWN,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
    "GRI 418-1-b": RequirementEvidenceContract(
        requirement_id="GRI 418-1-b",
        allowed_pages=(60, 61, 68),
        kpi_table_pages=(68,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.MANAGEMENT_MECHANISM, EvidenceKind.EXPLICIT_ZERO_STATEMENT),
        semantic_group=SemanticGroup.PRIVACY_MANAGEMENT,
        missing_items=("已识别客户数据泄露、被盗或丢失数量",),
    ),
    "GRI 418-1-c": RequirementEvidenceContract(
        requirement_id="GRI 418-1-c",
        allowed_pages=(61,),
        candidate_pages=(61,),
        facets=(RequirementFacet.REQUIRES_COUNT,),
        evidence_kinds=(EvidenceKind.EXPLICIT_ZERO_STATEMENT,),
        semantic_group=SemanticGroup.ZERO_EVENT_COMPLIANCE,
    ),
}


def get_requirement_contract(requirement_id: str) -> RequirementEvidenceContract | None:
    return _CONTRACTS.get(requirement_id)
