from dataclasses import dataclass

from src.domain.enums import AssessmentVerdict, ReviewStatus


@dataclass(frozen=True)
class RequirementEvidenceContract:
    requirement_id: str
    allowed_pages: tuple[int, ...] = ()
    forbidden_pages: tuple[int, ...] = ()
    candidate_pages: tuple[int, ...] | None = None
    kpi_table_pages: tuple[int, ...] = ()
    verdict: AssessmentVerdict | None = None
    review_status: ReviewStatus | None = None
    rationale: str | None = None
    missing_items: tuple[str, ...] = ()


_CONTRACTS: dict[str, RequirementEvidenceContract] = {
    "GRI 305-1-a": RequirementEvidenceContract(
        requirement_id="GRI 305-1-a",
        allowed_pages=(20, 63),
        forbidden_pages=(3,),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded evidence directly discloses Scope 1 GHG emissions.",
    ),
    "GRI 305-1-e": RequirementEvidenceContract(
        requirement_id="GRI 305-1-e",
        allowed_pages=(64,),
        candidate_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes GHG emission factors and GWP sources, but requires manual sufficiency review.",
        missing_items=("温室气体种类", "完整排放因子来源", "完整 GWP 来源"),
    ),
    "GRI 305-1-g": RequirementEvidenceContract(
        requirement_id="GRI 305-1-g",
        allowed_pages=(64,),
        candidate_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes GHG calculation methods or standards, but does not fully establish all methodology details.",
        missing_items=("完整核算标准", "完整方法说明"),
    ),
    "GRI 305-2-a": RequirementEvidenceContract(
        requirement_id="GRI 305-2-a",
        allowed_pages=(20, 63),
        forbidden_pages=(3,),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded evidence directly discloses location-based Scope 2 GHG emissions.",
    ),
    "GRI 305-2-b": RequirementEvidenceContract(
        requirement_id="GRI 305-2-b",
        allowed_pages=(20, 63),
        forbidden_pages=(3,),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded evidence directly discloses market-based Scope 2 GHG emissions.",
    ),
    "GRI 305-2-c": RequirementEvidenceContract(
        requirement_id="GRI 305-2-c",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="The report does not explicitly list gases included in Scope 2 calculation.",
        missing_items=("温室气体种类",),
    ),
    "GRI 305-2-d": RequirementEvidenceContract(
        requirement_id="GRI 305-2-d",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="The report does not disclose Scope 2 base year and rationale.",
        missing_items=("基准年", "选择基准年的理由"),
    ),
    "GRI 305-2-d-i": RequirementEvidenceContract(
        requirement_id="GRI 305-2-d-i",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="The report does not disclose Scope 2 base year emissions.",
        missing_items=("基准年排放量",),
    ),
    "GRI 305-2-e": RequirementEvidenceContract(
        requirement_id="GRI 305-2-e",
        allowed_pages=(64,),
        candidate_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses Scope 2 emission factor sources, but it does not explicitly disclose GWP rates.",
        missing_items=("GWP rates", "完整排放因子适用口径"),
    ),
    "GRI 305-2-g": RequirementEvidenceContract(
        requirement_id="GRI 305-2-g",
        allowed_pages=(64,),
        forbidden_pages=(3,),
        candidate_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes Scope 2 GHG calculation methods and emission factor sources, but it does not fully establish all standards, methodologies, assumptions, and calculation tools.",
        missing_items=("完整核算标准", "完整方法、假设和计算工具"),
    ),
    "GRI 305-3-a": RequirementEvidenceContract(
        requirement_id="GRI 305-3-a",
        allowed_pages=(20, 63),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded evidence directly discloses total Scope 3 GHG emissions.",
    ),
    "GRI 305-3-f": RequirementEvidenceContract(
        requirement_id="GRI 305-3-f",
        allowed_pages=(64,),
        candidate_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses Scope 3 calculation methods and emission factor sources, but it does not fully disclose GWP rates.",
        missing_items=("GWP rates", "完整范围三排放因子口径"),
    ),
    "GRI 305-5-a": RequirementEvidenceContract(
        requirement_id="GRI 305-5-a",
        allowed_pages=(63,),
        candidate_pages=(63,),
        kpi_table_pages=(63,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded KPI evidence directly discloses GHG emissions reduced as a result of reduction initiatives.",
    ),
    "GRI 305-7-a": RequirementEvidenceContract(
        requirement_id="GRI 305-7-a",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Waste management text and water pollutant KPI rows do not substantively disclose significant air emissions such as NOx, SOx, POP, VOC, HAP, or PM.",
        missing_items=("NOx/SOx 等重大气体排放数据", "空气污染物类别拆分"),
    ),
    "GRI 306-1-a": RequirementEvidenceContract(
        requirement_id="GRI 306-1-a",
        allowed_pages=(21, 22),
        candidate_pages=(21, 22),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes waste management practices and selected waste-related impacts, but it does not fully identify all actual and potential significant waste-related impacts.",
        missing_items=("完整重大影响识别", "上下游边界说明"),
    ),
    "GRI 306-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 306-1-a-i",
        allowed_pages=(21,),
        candidate_pages=(21,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes selected inputs, activities, and outputs related to waste, but it does not fully map waste-related impacts.",
        missing_items=("完整 input/activity/output 映射",),
    ),
    "GRI 306-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 306-1-a-ii",
        allowed_pages=(21,),
        candidate_pages=(21,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes own activities and selected supplier packaging loops, but it does not fully disclose upstream and downstream waste-related impacts.",
        missing_items=("完整价值链废弃物影响边界",),
    ),
    "GRI 306-2-a": RequirementEvidenceContract(
        requirement_id="GRI 306-2-a",
        allowed_pages=(21,),
        candidate_pages=(21,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes 5R principles and waste reduction or reuse initiatives, but it does not fully disclose all actions taken to prevent waste generation and manage impacts.",
        missing_items=("完整行动清单", "覆盖范围和效果"),
    ),
    "GRI 306-2-b": RequirementEvidenceContract(
        requirement_id="GRI 306-2-b",
        allowed_pages=(21,),
        candidate_pages=(21,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes review and supervision of waste disposal suppliers, but it does not fully disclose third-party waste management process coverage.",
        missing_items=("第三方处置过程完整说明", "覆盖范围和审查标准"),
    ),
    "GRI 306-3-a": RequirementEvidenceContract(
        requirement_id="GRI 306-3-a",
        allowed_pages=(64,),
        candidate_pages=(64,),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded KPI evidence discloses hazardous and non-hazardous waste weights, but it does not fully disclose waste composition or compilation context.",
        missing_items=("废弃物组成", "数据编制上下文"),
    ),
    "GRI 306-4-a": RequirementEvidenceContract(
        requirement_id="GRI 306-4-a",
        allowed_pages=(64,),
        candidate_pages=(64,),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded KPI evidence discloses total waste recovered and recovery rate, but it does not fully break down recovery operations.",
        missing_items=("recovery operation 拆分", "处置去向拆分"),
    ),
    "GRI 306-4-b": RequirementEvidenceContract(
        requirement_id="GRI 306-4-b",
        allowed_pages=(64,),
        candidate_pages=(64,),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded KPI evidence discloses hazardous waste recovery totals and rates, but it does not fully break down recovery operations.",
        missing_items=("危险废弃物 recovery operation 拆分",),
    ),
    "GRI 306-4-c": RequirementEvidenceContract(
        requirement_id="GRI 306-4-c",
        allowed_pages=(64,),
        candidate_pages=(64,),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded KPI evidence discloses non-hazardous waste recovery totals and rates, but it does not fully break down recovery operations.",
        missing_items=("非危险废弃物 recovery operation 拆分",),
    ),
    "GRI 306-4-b-i": RequirementEvidenceContract(
        requirement_id="GRI 306-4-b-i",
        allowed_pages=(21, 64),
        candidate_pages=(21, 64),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes reuse practices, but it does not provide the total weight of waste prepared for reuse.",
        missing_items=("回用废弃物总重量", "处置去向或场内外拆分"),
    ),
    "GRI 306-4-c-i": RequirementEvidenceContract(
        requirement_id="GRI 306-4-c-i",
        allowed_pages=(21, 64),
        candidate_pages=(21, 64),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes reuse practices, but it does not provide the total weight of waste prepared for reuse.",
        missing_items=("回用废弃物总重量", "处置去向或场内外拆分"),
    ),
}


def get_requirement_contract(requirement_id: str) -> RequirementEvidenceContract | None:
    return _CONTRACTS.get(requirement_id)
