from dataclasses import dataclass

from src.domain.enums import AssessmentVerdict, ReviewStatus


@dataclass(frozen=True)
class RequirementEvidenceContract:
    requirement_id: str
    allowed_pages: tuple[int, ...] = ()
    forbidden_pages: tuple[int, ...] = ()
    candidate_pages: tuple[int, ...] | None = None
    kpi_table_pages: tuple[int, ...] = ()
    verdict: AssessmentVerdict | None = None
    review_status: ReviewStatus | None = None
    rationale: str | None = None
    missing_items: tuple[str, ...] = ()


_CONTRACTS: dict[str, RequirementEvidenceContract] = {
    "GRI 305-1-a": RequirementEvidenceContract(
        requirement_id="GRI 305-1-a",
        allowed_pages=(20, 63),
        forbidden_pages=(3,),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded evidence directly discloses Scope 1 GHG emissions.",
    ),
    "GRI 305-1-e": RequirementEvidenceContract(
        requirement_id="GRI 305-1-e",
        allowed_pages=(64,),
        candidate_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes GHG emission factors and GWP sources, but requires manual sufficiency review.",
        missing_items=("温室气体种类", "完整排放因子来源", "完整 GWP 来源"),
    ),
    "GRI 305-1-g": RequirementEvidenceContract(
        requirement_id="GRI 305-1-g",
        allowed_pages=(64,),
        candidate_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes GHG calculation methods or standards, but does not fully establish all methodology details.",
        missing_items=("完整核算标准", "完整方法说明"),
    ),
    "GRI 305-2-a": RequirementEvidenceContract(
        requirement_id="GRI 305-2-a",
        allowed_pages=(20, 63),
        forbidden_pages=(3,),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded evidence directly discloses location-based Scope 2 GHG emissions.",
    ),
    "GRI 305-2-b": RequirementEvidenceContract(
        requirement_id="GRI 305-2-b",
        allowed_pages=(20, 63),
        forbidden_pages=(3,),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded evidence directly discloses market-based Scope 2 GHG emissions.",
    ),
    "GRI 305-2-c": RequirementEvidenceContract(
        requirement_id="GRI 305-2-c",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="The report does not explicitly list gases included in Scope 2 calculation.",
        missing_items=("温室气体种类",),
    ),
    "GRI 305-2-d": RequirementEvidenceContract(
        requirement_id="GRI 305-2-d",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="The report does not disclose Scope 2 base year and rationale.",
        missing_items=("基准年", "选择基准年的理由"),
    ),
    "GRI 305-2-d-i": RequirementEvidenceContract(
        requirement_id="GRI 305-2-d-i",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="The report does not disclose Scope 2 base year emissions.",
        missing_items=("基准年排放量",),
    ),
    "GRI 305-2-e": RequirementEvidenceContract(
        requirement_id="GRI 305-2-e",
        allowed_pages=(64,),
        candidate_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses Scope 2 emission factor sources, but it does not explicitly disclose GWP rates.",
        missing_items=("GWP rates", "完整排放因子适用口径"),
    ),
    "GRI 305-2-g": RequirementEvidenceContract(
        requirement_id="GRI 305-2-g",
        allowed_pages=(64,),
        forbidden_pages=(3,),
        candidate_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes Scope 2 GHG calculation methods and emission factor sources, but it does not fully establish all standards, methodologies, assumptions, and calculation tools.",
        missing_items=("完整核算标准", "完整方法、假设和计算工具"),
    ),
    "GRI 305-3-a": RequirementEvidenceContract(
        requirement_id="GRI 305-3-a",
        allowed_pages=(20, 63),
        candidate_pages=(20, 63),
        kpi_table_pages=(63,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded evidence directly discloses total Scope 3 GHG emissions.",
    ),
    "GRI 305-3-f": RequirementEvidenceContract(
        requirement_id="GRI 305-3-f",
        allowed_pages=(64,),
        candidate_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses Scope 3 calculation methods and emission factor sources, but it does not fully disclose GWP rates.",
        missing_items=("GWP rates", "完整范围三排放因子口径"),
    ),
    "GRI 305-5-a": RequirementEvidenceContract(
        requirement_id="GRI 305-5-a",
        allowed_pages=(63,),
        candidate_pages=(63,),
        kpi_table_pages=(63,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded KPI evidence directly discloses GHG emissions reduced as a result of reduction initiatives.",
    ),
    "GRI 305-7-a": RequirementEvidenceContract(
        requirement_id="GRI 305-7-a",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Waste management text and water pollutant KPI rows do not substantively disclose significant air emissions such as NOx, SOx, POP, VOC, HAP, or PM.",
        missing_items=("NOx/SOx 等重大气体排放数据", "空气污染物类别拆分"),
    ),
    "GRI 306-1-a": RequirementEvidenceContract(
        requirement_id="GRI 306-1-a",
        allowed_pages=(21, 22),
        candidate_pages=(21, 22),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes waste management practices and selected waste-related impacts, but it does not fully identify all actual and potential significant waste-related impacts.",
        missing_items=("完整重大影响识别", "上下游边界说明"),
    ),
    "GRI 306-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 306-1-a-i",
        allowed_pages=(21,),
        candidate_pages=(21,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes selected inputs, activities, and outputs related to waste, but it does not fully map waste-related impacts.",
        missing_items=("完整 input/activity/output 映射",),
    ),
    "GRI 306-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 306-1-a-ii",
        allowed_pages=(21,),
        candidate_pages=(21,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes own activities and selected supplier packaging loops, but it does not fully disclose upstream and downstream waste-related impacts.",
        missing_items=("完整价值链废弃物影响边界",),
    ),
    "GRI 306-2-a": RequirementEvidenceContract(
        requirement_id="GRI 306-2-a",
        allowed_pages=(21,),
        candidate_pages=(21,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes 5R principles and waste reduction or reuse initiatives, but it does not fully disclose all actions taken to prevent waste generation and manage impacts.",
        missing_items=("完整行动清单", "覆盖范围和效果"),
    ),
    "GRI 306-2-b": RequirementEvidenceContract(
        requirement_id="GRI 306-2-b",
        allowed_pages=(21,),
        candidate_pages=(21,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes review and supervision of waste disposal suppliers, but it does not fully disclose third-party waste management process coverage.",
        missing_items=("第三方处置过程完整说明", "覆盖范围和审查标准"),
    ),
    "GRI 306-3-a": RequirementEvidenceContract(
        requirement_id="GRI 306-3-a",
        allowed_pages=(64,),
        candidate_pages=(64,),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded KPI evidence discloses hazardous and non-hazardous waste weights, but it does not fully disclose waste composition or compilation context.",
        missing_items=("废弃物组成", "数据编制上下文"),
    ),
    "GRI 306-4-a": RequirementEvidenceContract(
        requirement_id="GRI 306-4-a",
        allowed_pages=(64,),
        candidate_pages=(64,),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded KPI evidence discloses total waste recovered and recovery rate, but it does not fully break down recovery operations.",
        missing_items=("recovery operation 拆分", "处置去向拆分"),
    ),
    "GRI 306-4-b": RequirementEvidenceContract(
        requirement_id="GRI 306-4-b",
        allowed_pages=(64,),
        candidate_pages=(64,),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded KPI evidence discloses hazardous waste recovery totals and rates, but it does not fully break down recovery operations.",
        missing_items=("危险废弃物 recovery operation 拆分",),
    ),
    "GRI 306-4-c": RequirementEvidenceContract(
        requirement_id="GRI 306-4-c",
        allowed_pages=(64,),
        candidate_pages=(64,),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded KPI evidence discloses non-hazardous waste recovery totals and rates, but it does not fully break down recovery operations.",
        missing_items=("非危险废弃物 recovery operation 拆分",),
    ),
    "GRI 306-4-b-i": RequirementEvidenceContract(
        requirement_id="GRI 306-4-b-i",
        allowed_pages=(21, 64),
        candidate_pages=(21, 64),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes reuse practices, but it does not provide the total weight of waste prepared for reuse.",
        missing_items=("回用废弃物总重量", "处置去向或场内外拆分"),
    ),
    "GRI 306-4-c-i": RequirementEvidenceContract(
        requirement_id="GRI 306-4-c-i",
        allowed_pages=(21, 64),
        candidate_pages=(21, 64),
        kpi_table_pages=(64,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes reuse practices, but it does not provide the total weight of waste prepared for reuse.",
        missing_items=("回用废弃物总重量", "处置去向或场内外拆分"),
    ),
    "GRI 308-1-a": RequirementEvidenceContract(
        requirement_id="GRI 308-1-a",
        allowed_pages=(67,),
        candidate_pages=(67,),
        kpi_table_pages=(67,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded KPI evidence directly discloses the percentage of new suppliers screened using environmental criteria.",
    ),
    "GRI 308-2-a": RequirementEvidenceContract(
        requirement_id="GRI 308-2-a",
        allowed_pages=(67,),
        candidate_pages=(67,),
        kpi_table_pages=(67,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded KPI evidence directly discloses the number of suppliers assessed for environmental impacts.",
    ),
    "GRI 308-2-b": RequirementEvidenceContract(
        requirement_id="GRI 308-2-b",
        allowed_pages=(67,),
        candidate_pages=(67,),
        kpi_table_pages=(67,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded KPI evidence directly discloses suppliers identified as having significant actual or potential negative environmental impacts.",
    ),
    "GRI 308-2-c": RequirementEvidenceContract(
        requirement_id="GRI 308-2-c",
        allowed_pages=(52, 67),
        candidate_pages=(52, 67),
        kpi_table_pages=(67,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded KPI evidence indicates no suppliers with significant environmental impacts, but it does not fully describe the types of significant impacts identified in the supply chain.",
        missing_items=("供应链重大环境影响类型",),
    ),
    "GRI 308-2-d": RequirementEvidenceContract(
        requirement_id="GRI 308-2-d",
        allowed_pages=(67,),
        candidate_pages=(67,),
        kpi_table_pages=(67,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded KPI evidence directly discloses the percentage of suppliers with significant environmental impacts where improvements were agreed after assessment.",
    ),
    "GRI 308-2-e": RequirementEvidenceContract(
        requirement_id="GRI 308-2-e",
        allowed_pages=(54, 67),
        candidate_pages=(54, 67),
        kpi_table_pages=(67,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses supplier termination percentage after assessment and describes supplier exit mechanisms, but it does not fully explain why relationships were terminated.",
        missing_items=("终止关系原因说明",),
    ),
    "GRI 401-1-a": RequirementEvidenceContract(
        requirement_id="GRI 401-1-a",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses new employee hires by gender and age, but it does not provide regional breakdowns.",
        missing_items=("地区拆分",),
    ),
    "GRI 401-1-b": RequirementEvidenceContract(
        requirement_id="GRI 401-1-b",
        allowed_pages=(33, 65),
        candidate_pages=(33, 65),
        kpi_table_pages=(65,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses employee turnover by gender and age, but it does not provide regional breakdowns.",
        missing_items=("地区拆分",),
    ),
    "GRI 401-2-a": RequirementEvidenceContract(
        requirement_id="GRI 401-2-a",
        allowed_pages=(34,),
        candidate_pages=(34,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses employee benefits, but it does not compare full-time employees with temporary or part-time employees by significant operating locations.",
        missing_items=("全职与临时/兼职员工福利差异", "significant locations of operation"),
    ),
    "GRI 401-2-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 401-2-a-ii",
        allowed_pages=(34,),
        candidate_pages=(34,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses medical insurance and health benefits, but it does not compare employee categories by significant operating locations.",
        missing_items=("员工类别福利差异", "significant locations of operation"),
    ),
    "GRI 401-2-a-iv": RequirementEvidenceContract(
        requirement_id="GRI 401-2-a-iv",
        allowed_pages=(34,),
        candidate_pages=(34,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses paid leave and parental leave, but it does not compare employee categories by significant operating locations.",
        missing_items=("员工类别福利差异", "significant locations of operation"),
    ),
    "GRI 401-2-a-vii": RequirementEvidenceContract(
        requirement_id="GRI 401-2-a-vii",
        allowed_pages=(34,),
        candidate_pages=(34,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses supplemental housing and family support benefits, but it does not compare employee categories by significant operating locations.",
        missing_items=("员工类别福利差异", "significant locations of operation"),
    ),
    "GRI 401-3-c": RequirementEvidenceContract(
        requirement_id="GRI 401-3-c",
        allowed_pages=(66,),
        forbidden_pages=(32,),
        candidate_pages=(66,),
        kpi_table_pages=(66,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded KPI evidence directly discloses employees returning to work after parental leave by gender.",
    ),
    "GRI 401-3-d": RequirementEvidenceContract(
        requirement_id="GRI 401-3-d",
        allowed_pages=(66,),
        forbidden_pages=(32,),
        candidate_pages=(66,),
        kpi_table_pages=(66,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded KPI evidence directly discloses employees retained 12 months after returning from parental leave by gender.",
    ),
    "GRI 401-3-e": RequirementEvidenceContract(
        requirement_id="GRI 401-3-e",
        allowed_pages=(66,),
        forbidden_pages=(32,),
        candidate_pages=(66,),
        kpi_table_pages=(66,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded KPI evidence discloses overall return-to-work and retention rates, but it does not directly disclose these rates by gender.",
        missing_items=("按性别披露的返岗率和留任率",),
    ),
    "GRI 402-1-a": RequirementEvidenceContract(
        requirement_id="GRI 402-1-a",
        allowed_pages=(33, 66),
        candidate_pages=(33, 66),
        kpi_table_pages=(66,),
        verdict=AssessmentVerdict.DISCLOSED,
        review_status=ReviewStatus.NOT_REQUIRED,
        rationale="Bounded evidence directly discloses a four-week minimum notice period before significant operational changes.",
    ),
    "GRI 402-1-b": RequirementEvidenceContract(
        requirement_id="GRI 402-1-b",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="The report does not disclose whether notice and consultation provisions are specified in collective agreements.",
        missing_items=("集体协议中的通知期或协商安排",),
    ),
    "GRI 403-1-a": RequirementEvidenceContract(
        requirement_id="GRI 403-1-a",
        allowed_pages=(38, 39, 66),
        candidate_pages=(38, 39, 66),
        kpi_table_pages=(66,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes the OHS management system and ISO 45001 certification, but it does not fully disclose scope, coverage boundaries, or exclusions.",
        missing_items=("覆盖范围", "排除说明"),
    ),
    "GRI 403-1-a-i": RequirementEvidenceContract(
        requirement_id="GRI 403-1-a-i",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="The report references compliance with local OHS laws but does not list the legal requirements.",
        missing_items=("适用法律要求清单",),
    ),
    "GRI 403-1-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-1-a-ii",
        allowed_pages=(38, 39, 66),
        candidate_pages=(38, 39, 66),
        kpi_table_pages=(66,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes ISO 45001-oriented management system coverage, but it does not fully disclose all recognized standards or guidelines and scope.",
        missing_items=("完整标准/指南", "覆盖范围"),
    ),
    "GRI 403-1-b": RequirementEvidenceContract(
        requirement_id="GRI 403-1-b",
        allowed_pages=(38, 39, 66),
        candidate_pages=(38, 39, 66),
        kpi_table_pages=(66,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes OHS system coverage directionally, but it does not fully disclose worker, activity, and workplace coverage or exclusions.",
        missing_items=("人员、活动和工作场所覆盖范围", "排除说明"),
    ),
    "GRI 403-2-a": RequirementEvidenceContract(
        requirement_id="GRI 403-2-a",
        allowed_pages=(39, 41),
        candidate_pages=(39, 41),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes hazard identification, risk assessment, and incident management processes, but it does not fully disclose all process details.",
        missing_items=("完整流程和覆盖范围",),
    ),
    "GRI 403-2-a-i": RequirementEvidenceContract(
        requirement_id="GRI 403-2-a-i",
        allowed_pages=(39, 41),
        candidate_pages=(39, 41),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes hazard identification and risk assessment mechanisms, but it does not fully disclose routine and non-routine process details.",
        missing_items=("常规/非常规危害识别流程",),
    ),
    "GRI 403-2-a-ii": RequirementEvidenceContract(
        requirement_id="GRI 403-2-a-ii",
        allowed_pages=(39, 41),
        candidate_pages=(39, 41),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes worker hazard reporting and incident management, but it does not fully disclose all channels and protection mechanisms.",
        missing_items=("完整上报渠道", "保护机制"),
    ),
    "GRI 403-2-b": RequirementEvidenceContract(
        requirement_id="GRI 403-2-b",
        allowed_pages=(39, 41),
        candidate_pages=(39, 41),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes incident investigation and corrective action, but it does not fully disclose complete investigation processes.",
        missing_items=("事故调查流程细节",),
    ),
    "GRI 403-2-c": RequirementEvidenceContract(
        requirement_id="GRI 403-2-c",
        candidate_pages=(),
        verdict=AssessmentVerdict.UNKNOWN,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="The report does not disclose worker removal from dangerous work situations or retaliation protection.",
        missing_items=("危险工作情境撤离机制", "反报复保护"),
    ),
    "GRI 403-2-d": RequirementEvidenceContract(
        requirement_id="GRI 403-2-d",
        allowed_pages=(39, 41),
        candidate_pages=(39, 41),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes incident reporting and corrective action, but it does not fully disclose how investigations drive OHS management system improvements.",
        missing_items=("调查结果纳入体系改进的完整机制",),
    ),
    "GRI 403-3-a": RequirementEvidenceContract(
        requirement_id="GRI 403-3-a",
        allowed_pages=(38, 66, 67),
        candidate_pages=(38, 66, 67),
        kpi_table_pages=(66, 67),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes OHS technical committee and health-related KPIs, but it does not fully disclose occupational health service functions, quality assurance, or worker access.",
        missing_items=("职业健康服务职能", "质量保证", "员工获取方式"),
    ),
    "GRI 403-4-a": RequirementEvidenceContract(
        requirement_id="GRI 403-4-a",
        allowed_pages=(38, 39, 41, 66),
        candidate_pages=(38, 39, 41, 66),
        kpi_table_pages=(66,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes EHS committees and worker participation channels, but it does not fully disclose consultation mechanisms and decision authority.",
        missing_items=("委员会职责", "会议频率", "决策权限"),
    ),
    "GRI 403-4-b": RequirementEvidenceContract(
        requirement_id="GRI 403-4-b",
        allowed_pages=(38, 39, 41, 66),
        candidate_pages=(38, 39, 41, 66),
        kpi_table_pages=(66,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses worker representation in health and safety committees, but it does not fully disclose committee responsibilities or non-represented worker reasons.",
        missing_items=("委员会职责", "未代表员工原因"),
    ),
    "GRI 403-5-a": RequirementEvidenceContract(
        requirement_id="GRI 403-5-a",
        allowed_pages=(41, 66),
        candidate_pages=(41, 66),
        kpi_table_pages=(66,),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence describes EHS training objects, methods, courses, instructors, and assessments, but hazard-specific training detail is incomplete.",
        missing_items=("hazard-specific training 细节",),
    ),
    "GRI 403-6-a": RequirementEvidenceContract(
        requirement_id="GRI 403-6-a",
        allowed_pages=(34, 66, 67),
        candidate_pages=(34, 66, 67),
        kpi_table_pages=(66, 67),
        verdict=AssessmentVerdict.PARTIALLY_DISCLOSED,
        review_status=ReviewStatus.NEEDS_MANUAL_REVIEW,
        rationale="Bounded evidence discloses healthcare benefits and health check KPIs, but it does not fully disclose access methods and service scope.",
        missing_items=("获取方式", "服务范围"),
    ),
}


def get_requirement_contract(requirement_id: str) -> RequirementEvidenceContract | None:
    return _CONTRACTS.get(requirement_id)
