from __future__ import annotations

import argparse
import hashlib
import json
from datetime import date
from pathlib import Path
from typing import Any


def build_acceptance_summary(
    *,
    project_root: Path,
    output_path: Path,
    assets_manifest: Path,
    structure_summary_path: Path,
    ai_summary_path: Path,
    envision_summary_path: Path,
    goldwind_summary_path: Path,
    artifact_specs: list[tuple[str, Path]],
    git_head: str,
    backend_test_count: int,
    frontend_test_file_count: int,
    frontend_test_count: int,
) -> dict[str, Any]:
    artifacts = [
        _artifact_record(project_root, asset_type, path)
        for asset_type, path in artifact_specs
    ]
    summary = {
        "generated_at": date.today().isoformat(),
        "git_head_before_freeze_commit": git_head,
        "database": {
            "head": "0011_ai_suggestions",
            "main_head": "0011_ai_suggestions",
            "demo_head": "0011_ai_suggestions",
        },
        "structure": _read_json(structure_summary_path),
        "ai_evaluation": _read_json(ai_summary_path),
        "envision_regression": _read_json(envision_summary_path),
        "goldwind_gate": _read_json(goldwind_summary_path),
        "tests": {
            "backend_passed": backend_test_count,
            "frontend_test_files_passed": frontend_test_file_count,
            "frontend_tests_passed": frontend_test_count,
            "frontend_typecheck": "passed",
            "frontend_production_build": "passed",
        },
        "runtime_boundaries": {
            "external_model_default": "disabled",
            "deepseek_evaluation_explicitly_authorized": True,
            "ocr_enabled": False,
            "vlm_enabled": False,
            "ai_is_advisory": True,
            "gri_expert_certification": False,
        },
        "artifacts": artifacts,
        "summary_sha256_recorded_in_assets_manifest": True,
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    all_records = [
        *artifacts,
        _artifact_record(
            project_root,
            "backend_freeze_acceptance_summary",
            output_path,
        ),
    ]
    _register_assets(assets_manifest, all_records)
    return summary


def _artifact_record(
    project_root: Path,
    asset_type: str,
    path: Path,
) -> dict[str, Any]:
    content = path.read_bytes()
    return {
        "target_path": path.resolve().relative_to(project_root.resolve()).as_posix(),
        "sha256": hashlib.sha256(content).hexdigest(),
        "size_bytes": len(content),
        "asset_type": asset_type,
    }


def _register_assets(
    manifest_path: Path,
    records: list[dict[str, Any]],
) -> None:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    targets = {record["target_path"] for record in records}
    manifest["assets"] = [
        item
        for item in manifest.get("assets", [])
        if item.get("target_path") not in targets
    ]
    for record in records:
        is_backup = record["asset_type"] == "postgresql_backend_freeze_backup"
        manifest["assets"].append(
            {
                "source_path": (
                    "database snapshot created with pg_dump"
                    if is_backup
                    else "generated by backend freeze acceptance workflow"
                ),
                **record,
                "material_status": (
                    "runtime_backup" if is_backup else "derived_validation_data"
                ),
                "copied_at": date.today().isoformat(),
                "source_protection": (
                    "database was read with pg_dump; no source records were modified"
                    if is_backup
                    else "source report, standards, and manual review inputs were not modified"
                ),
            }
        )
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=4) + "\n",
        encoding="utf-8",
    )


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build the backend freeze acceptance summary.")
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--assets-manifest", type=Path, required=True)
    parser.add_argument("--structure-summary", type=Path, required=True)
    parser.add_argument("--ai-summary", type=Path, required=True)
    parser.add_argument("--envision-summary", type=Path, required=True)
    parser.add_argument("--goldwind-summary", type=Path, required=True)
    parser.add_argument("--artifact", action="append", default=[])
    parser.add_argument("--git-head", required=True)
    parser.add_argument("--backend-test-count", type=int, required=True)
    parser.add_argument("--frontend-test-file-count", type=int, required=True)
    parser.add_argument("--frontend-test-count", type=int, required=True)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    artifact_specs = []
    for value in args.artifact:
        asset_type, separator, path = value.partition("=")
        if not separator or not asset_type or not path:
            raise ValueError("--artifact must use asset_type=path")
        artifact_specs.append((asset_type, Path(path)))
    summary = build_acceptance_summary(
        project_root=args.project_root,
        output_path=args.output,
        assets_manifest=args.assets_manifest,
        structure_summary_path=args.structure_summary,
        ai_summary_path=args.ai_summary,
        envision_summary_path=args.envision_summary,
        goldwind_summary_path=args.goldwind_summary,
        artifact_specs=artifact_specs,
        git_head=args.git_head,
        backend_test_count=args.backend_test_count,
        frontend_test_file_count=args.frontend_test_file_count,
        frontend_test_count=args.frontend_test_count,
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
